export const USER_REQUEST = 'USER_REQUEST';
export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_ERROR = 'USER_ERROR';
export const USER_UPDATE_ERROR = 'USER_UPDATE_ERROR';
export const USER_LOGOUT = 'USER_LOGOUT';

export const BILL_REQUEST = 'BILL_REQUEST';
export const BILL_SUCCESS = 'BILL_SUCCESS';
export const BILL_LIST_SUCCESS = 'BILL_LIST_SUCCESS';
export const BILL_ERROR = 'BILL_ERROR';
export const BILL_UPDATE_ERROR = 'BILL_UPDATE_ERROR';
export const MONTH_ECONOMY_SUCCESS = 'MONTH_ECONOMY_SUCCESS';
export const CHART_SUCCESS = 'CHART_SUCCESS';
export const EMPTY_BILLS_DATA = 'EMPTY_BILLS_DATA';

export const TIPS_AND_TRICKS_REQUEST = 'TIPS_AND_TRICKS_REQUEST';
export const TIPS_AND_TRICKS_SUCCESS = 'TIPS_AND_TRICKS_SUCCESS';
export const TIPS_AND_TRICKS_RANDOM_SUCCESS = 'TIPS_AND_TRICKS_RANDOM_SUCCESS';
export const TIPS_AND_TRICKS_ERROR = 'TIPS_AND_TRICKS_ERROR';

export const QUESTION_REQUEST = 'QUESTION_REQUEST';
export const QUESTION_SUCCESS = 'QUESTION_SUCCESS';
export const ANSWER_SUCCESS = 'ANSWER_SUCCESS';
export const QUESTION_ERROR = 'QUESTION_ERROR';