export const USER_REQUEST = 'USER_REQUEST';
export const USER_SUCCESS = 'USER_SUCCESS';
export const USER_ERROR = 'USER_ERROR';
export const USER_UPDATE_ERROR = 'USER_UPDATE_ERROR';
export const USER_LOGOUT = 'USER_LOGOUT';

export const BILL_REQUEST = 'BILL_REQUEST';
export const BILL_SUCCESS = 'BILL_SUCCESS';
export const BILL_ERROR = 'BILL_ERROR';
export const BILL_UPDATE_ERROR = 'BILL_UPDATE_ERROR';

export const TIPS_AND_TRICKS_REQUEST = 'TIPS_AND_TRICKS_REQUEST';
export const TIPS_AND_TRICKS_SUCCESS = 'TIPS_AND_TRICKS_SUCCESS';
export const TIPS_AND_TRICKS_RANDOM_SUCCESS = 'TIPS_AND_TRICKS_RANDOM_SUCCESS';
export const TIPS_AND_TRICKS_ERROR = 'TIPS_AND_TRICKS_ERROR';